services:
  database:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - database_data:/data/db

  api:
    build:
      context: ./api
    command: npm run start
    environment:
      PORT: 4000
      MONGO_URL: mongodb://root:example@database:27017/trivia?authSource=admin
    depends_on:
      - database

  client:
    build:
      context: ./client
    depends_on:
      - api

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  database_data:
